[package]
name = "chess_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#![cfg(debug_assertions, allow(dead_code))]

[dependencies]
bevy = "*"
bevy-inspector-egui = "0.23.4"
rand = "0.8.5"
